/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enriquee
 */
public class CalcDatos extends javax.swing.JFrame {

    /**
     * Creates new form CalcDatos
     */
    public CalcDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblEdad = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtAltura = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtEdad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(0, 100, 171));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdad.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        lblEdad.setText("Edad");
        pnlPrincipal.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 30));

        lblAltura.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        lblAltura.setText("Altura");
        pnlPrincipal.add(lblAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, 30));

        lblPeso.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        lblPeso.setText("Peso");
        pnlPrincipal.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, 30));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "Masculino", "Femenino" }));
        pnlPrincipal.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, 20));

        txtPeso.setBackground(new java.awt.Color(0, 100, 171));
        txtPeso.setBorder(null);
        pnlPrincipal.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, 20));
        pnlPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 10));

        txtAltura.setBackground(new java.awt.Color(0, 100, 171));
        txtAltura.setBorder(null);
        pnlPrincipal.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, 20));
        pnlPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, 10));

        txtEdad.setBackground(new java.awt.Color(0, 100, 171));
        txtEdad.setBorder(null);
        pnlPrincipal.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 20));
        pnlPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
